### ISSUE TITLE
Sort returned 'names' on first_name

### ISSUE THREAD

**Issue by briangonzalez** [geni/geni-gedcom#5]
The user-exp. of selecting from a sorted list will be much better than a seemingly random one. Let's sort the returned `names` array on `first_name`

**Comment by briangonzalez** [comment]
@Raynes No rush, but we'll need this by end-of-day Wednesday :)

**Comment by Raynes** [comment]
@briangonzalez Oh my God. A deadline. Oh my God. I can't breathe. I can't take the pressure, I quit!!!!

**Comment by briangonzalez** [comment]
Well, then. I quit too!

On Tue, Jul 31, 2012 at 3:50 PM, Anthony Grimes <
reply@reply.github.com

**Comment by Raynes** [comment]
Did this.

@briangonzalez I've changed things a bit. Instead of returning `names` as a hash of ids to hashes I'm returning an array of hashes with the same keys as before, but with an added `id` key. See the updated index.html for example. Shouldn't be a big change on your part but is easier to work with on my side with sorting.

I'll let you know as soon as I can get this deployed.

**Comment by briangonzalez** [comment]
10-4 @Raynes
